export { default as Home } from './home/Home';
export { default as PaymentMethods } from './paymentMethods/PaymentMethods';
export { default as Contac} from './contact/PageContact';
export { default as MiPortal} from './miPortal/MiPortal';
export { default as Companies } from './companies/Companies';
export { default as Dashboard } from './dashboard/Home';
export { default as Users } from './users/Users';
export { default as Inquiries } from './inquiries/Inquiries';
export { default as Tiabaya } from './districts/Tiabaya';
export { default as Yanahuara } from './districts/Yanahuara';
export { default as PageAboutus } from './companies/PageAboutus';
export { default as PageRegulation } from './companies/PageRegutacion';
export { default as PageFiberOpticCoverage } from './companies/PageFiberOpticCoverage';
